# Generated by Django 5.2.6 on 2025-09-11 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_movimiento_fecha_alter_movimiento_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='categoria',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
